### ISSUE TITLE
Is segfault-handler required?

### ISSUE THREAD

**Issue by Ramzeus** [christian-raedel/nightlife-rabbit#2]
I cannot get segfault-handler to compile on Windows and therefore I cannot use nightlife-rabbit either. Is it really needed?
See this issue: https://github.com/ddopson/node-segfault-handler/issues/21

**Comment by christian-raedel** [comment]
Hi,

I removed **segfault-handler** from dependencies.
Which node version do you use? On my development-system, nightlife-rabbits tests run only on node v0.10 without segfault. This is websocket **ws** related.

Regards,
Christian

**Comment by Ramzeus** [comment]
I use NodeJS v0.12.0 Win64. The compiler was VS 2012, but I think the compiler doesn't matter.
Thanks anyway, I removed it locally a couple of hours ago (removed the dependency and the reference in router.js) and I got it to work :)

I ran in to another problem however, but I don't think it's nightlife-rabbits fault. I couldn't connect to the server from my browser (Chrome 40.0.2214.115) because the server couldn't parse the HELLO message from my client (I tried several, same problem). This is the log message I got:
>[March 3rd 2015, 14:46:55] [NightlifeRouter] +  10ms - DEBUG:   Socket message 1,localhost,[object Object]
1,localhost,[object Object]
>[March 3rd 2015, 14:46:55] [NightlifeRouter] +   3ms - ERROR:   Session parse error! TypeError: wamp.error.invalid_json
    at c:\Klocktornet\DISEServerWebUI\node_modules\nightlife-rabbit\lib\message-parser.js:170:19
    at Promise.apply (c:\Klocktornet\DISEServerWebUI\node_modules\nightlife-rabbit\node_modules\q\q.js:1107:26)
    at Promise.promise.promiseDispatch (c:\Klocktornet\DISEServerWebUI\node_modules\nightlife-rabbit\node_modules\q\q.js:748:41)
    at c:\Klocktornet\DISEServerWebUI\node_modules\nightlife-rabbit\node_modules\q\q.js:1333:14
    at flush (c:\Klocktornet\DISEServerWebUI\node_modules\nightlife-rabbit\node_modules\q\q.js:110:17)
    at process._tickCallback (node.js:355:11)
>[March 3rd 2015, 14:46:55] [NightlifeRouter] +   4ms - DEBUG:   Removing session from realm undefined
>[March 3rd 2015, 14:46:55] [NightlifeRouter] +   3ms - DEBUG:   Trying to send message [6, {"message":"Close connection"}, "wamp.error.internal_server_error"]
>[March 3rd 2015, 14:46:55] [NightlifeRouter] +   3ms - DEBUG:   GOODBYE message sent [6, {"message":"Close connection"}, "wamp.error.internal_server_error"]
>[March 3rd 2015, 14:47:04] [NightlifeRouter] +9129ms - DEBUG:   Socket close 1001
>[March 3rd 2015, 14:47:04] [NightlifeRouter] +   3ms - DEBUG:   Removing session from realm undefined

I checked what was transferred "on the wire" and it also didn't look like valid JSON (same as in the log row above). I traced the problem to the browsers WebSocket object send() method. The input was valid JSON but the output looks semi-parsed somehow. If I added invalid JSON data (just added the letter 'a' at the end) it would be transferred correctly (as text). Like this (of course it will be an error):
>[1,"localhost",{"agent":"Wampy.js v1.0.5","roles":{"publisher":{"features":{"subscriber_blackwhite_listing":true,"publisher_exclusion":true,"publisher_identification":true}},"subscriber":{},"caller":{"features":{"callee_blackwhite_listing":true,"caller_exclusion":true,"caller_identification":true,"progressive_call_results":true,"call_canceling":true}},"callee":{"features":{"caller_identification":true}}}}]a
>[March 3rd 2015, 14:47:04] [NightlifeRouter] +   5ms - ERROR:   Session parse error! TypeError: wamp.error.invalid_json

Super strange... have you seen anything like this before?

**Comment by Ramzeus** [comment]
Sorry for polluting the Issue with off-topic stuff, but it turned out to be an extension I had installed in my browser (Socket Puppet). It was messing with the communication.
