### ISSUE TITLE
register this package on https://www.npmjs.com

### ISSUE THREAD

**Issue by RafaelKa** [christian-raedel/nightlife-rabbit#3]
To provide npm installing way please register on https://www.npmjs.com and create release.

**Comment by christian-raedel** [comment]
Hi,

to add ```nightlife-rabbit``` as dependency to your project's ```package.json```, you can also install it with:

```
npm install --save https+git://github.com/christian-raedel/nightlife-rabbit
```

This package is not in the **npm-registry** yet, because I think it needs more tests in ```node``` **v0.11** and **v0.12** environments.

Regards,
Christian

**Comment by RafaelKa** [comment]
OK, i understand. 
I did it as follows in `package.json`:
```
//...
"dependencies": {
  //...
  "nightlife-rabbit": "git://github.com/christian-raedel/nightlife-rabbit.git#master"
  //...
}
//...

```
